### ISSUE TITLE
Export from pinecone seems to be a little bit hacky

### ISSUE THREAD

**Issue by xiaofan-luan** [AI-Northstar-Tech/vector-io#51]
Thanks team for the great work!

When I go through pinecone's exporter, it seems that there is no guarantee that the exporter can get all data.
Any experiments about how fast and accurate we can get when we export from pinecone?

**Comment by dhruv-anand-aintech** [comment]
Hi @xiaofan-luan, thanks for raising this. 
I flag this to the user in case the random searches approach doesn't work: https://github.com/AI-Northstar-Tech/vector-io/blob/512087506f421fe73cf49b4a13b6756ceb2190fc/src/vdf_io/export_vdf/pinecone_export.py#L295-L299

In my trials, using random searches approach is sufficient to extract all the points in the index when there are up to ~90k points in the index (takes ~20 tries). I have not tried with indexes much larger than that. There is an even more thorough approach which involves marking metadata on the points that have been downloaded (https://github.com/AI-Northstar-Tech/vector-io/blob/512087506f421fe73cf49b4a13b6756ceb2190fc/src/vdf_io/export_vdf/pinecone_export.py#L45-L51) using --modify_to_search, but it is more time-consuming due to Pinecone's rate-limiting on these operations.

The good news is that Pinecone has recently released a list vectors endpoint (https://docs.pinecone.io/docs/get-record-ids), but it is only for serverless indexes through the REST API for now. When they release it for pod-based indexes as well, and with python client support, I will switch to that method.

**Comment by xiaofan-luan** [comment]
Good to know! 
If there are some common storage format  that can be shared between different vectordbs that would be great
